import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MvFranca | Portfólio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      
      <body className={inter.className}>
        {children}
        <Navbar/>
      </body>
    </html>
  )
}
